title: "Guia do Exame AWS Solutions Architect Associate"
description: "Um guia abrangente para se preparar para a Certificação AWS Solutions Architect Associate"
theme: jekyll-theme-slate

nav:
  - title: "Português"
    nav:
      - title: "Introdução"
        url: /docs/pt/introducao/

      - title: "Design de Arquiteturas Resilientes"
        url: /docs/pt/design-arquiteturas-resilientes/

      - title: "Design de Arquiteturas de Alto Desempenho"
        url: /docs/pt/design-arquiteturas-alto-desempenho/

      - title: "Design de Aplicações Seguras"
        url: /docs/pt/design-aplicacoes-seguras/

      - title: "Design de Arquiteturas Otimizadas"
        url: /docs/pt/design-arquiteturas-otimizadas/

      - title: "Recursos Adicionais"
        url: /docs/pt/recursos-adicionais/

      - title: "Conclusão"
        url: /docs/pt/conclusao/

services:
  - category: "Analytics"
    services:
      - title: "Amazon Athena"
        url: /docs/pt/services/athena.md
      - title: "AWS Data Exchange"
        url: /docs/pt/services/data-exchange.md
      - title: "AWS Data Pipeline"
        url: /docs/pt/services/data-pipeline.md
      - title: "Amazon EMR"
        url: /docs/pt/services/emr.md
      - title: "AWS Glue"
        url: /docs/pt/services/glue.md
      - title: "Amazon Kinesis"
        url: /docs/pt/services/kinesis.md
      - title: "AWS Lake Formation"
        url: /docs/pt/services/lake-formation.md
      - title: "Amazon Managed Streaming for Apache Kafka (Amazon MSK)"
        url: /docs/pt/services/msk.md
      - title: "Amazon OpenSearch Service"
        url: /docs/pt/services/opensearch.md
      - title: "Amazon QuickSight"
        url: /docs/pt/services/quicksight.md
      - title: "Amazon Redshift"
        url: /docs/pt/services/redshift.md
  - category: "Application Integration"
    services:
      - title: "Amazon AppFlow"
        url: /docs/pt/services/appflow.md
      - title: "AWS AppSync"
        url: /docs/pt/services/appsync.md
      - title: "Amazon EventBridge"
        url: /docs/pt/services/eventbridge.md
      - title: "Amazon MQ"
        url: /docs/pt/services/mq.md
      - title: "Amazon Simple Notification Service (Amazon SNS)"
        url: /docs/pt/services/sns.md
      - title: "Amazon Simple Queue Service (Amazon SQS)"
        url: /docs/pt/services/sqs.md
      - title: "AWS Step Functions"
        url: /docs/pt/services/step-functions.md
  - category: "AWS Cost Management"
    services:
      - title: "AWS Budgets"
        url: /docs/pt/services/budgets.md
      - title: "AWS Cost and Usage Report"
        url: /docs/pt/services/cost-and-usage-report.md
      - title: "AWS Cost Explorer"
        url: /docs/pt/services/cost-explorer.md
      - title: "Savings Plans"
        url: /docs/pt/services/savings-plans.md
  - category: "Compute"
    services:
      - title: "AWS Batch"
        url: /docs/pt/services/batch.md
      - title: "Amazon EC2"
        url: /docs/pt/services/ec2.md
      - title: "Amazon EC2 Auto Scaling"
        url: /docs/pt/services/ec2-auto-scaling.md
      - title: "AWS Elastic Beanstalk"
        url: /docs/pt/services/elastic-beanstalk.md
      - title: "AWS Outposts"
        url: /docs/pt/services/outposts.md
      - title: "AWS Serverless Application Repository"
        url: /docs/pt/services/serverless-application-repository.md
      - title: "VMware Cloud on AWS"
        url: /docs/pt/services/vmware-cloud.md
      - title: "AWS Wavelength"
        url: /docs/pt/services/wavelength.md
  - category: "Containers"
    services:
      - title: "Amazon ECS Anywhere"
        url: /docs/pt/services/ecs-anywhere.md
      - title: "Amazon EKS Anywhere"
        url: /docs/pt/services/eks-anywhere.md
      - title: "Amazon EKS Distro"
        url: /docs/pt/services/eks-distro.md
      - title: "Amazon Elastic Container Registry (Amazon ECR)"
        url: /docs/pt/services/ecr.md
      - title: "Amazon Elastic Container Service (Amazon ECS)"
        url: /docs/pt/services/ecs.md
      - title: "Amazon Elastic Kubernetes Service (Amazon EKS)"
        url: /docs/pt/services/eks.md
  - category: "Database"
    services:
      - title: "Amazon Aurora"
        url: /docs/pt/services/aurora.md
      - title: "Amazon Aurora Serverless"
        url: /docs/pt/services/aurora-serverless.md
      - title: "Amazon DocumentDB (with MongoDB compatibility)"
        url: /docs/pt/services/documentdb.md
      - title: "Amazon DynamoDB"
        url: /docs/pt/services/dynamodb.md
      - title: "Amazon ElastiCache"
        url: /docs/pt/services/elasticache.md
      - title: "Amazon Keyspaces (for Apache Cassandra)"
        url: /docs/pt/services/keyspaces.md
      - title: "Amazon Neptune"
        url: /docs/pt/services/neptune.md
      - title: "Amazon Quantum Ledger Database (Amazon QLDB)"
        url: /docs/pt/services/qldb.md
      - title: "Amazon RDS"
        url: /docs/pt/services/rds.md
      - title: "Amazon Redshift"
        url: /docs/pt/services/redshift.md
  - category: "Developer Tools"
    services:
      - title: "AWS X-Ray"
        url: /docs/pt/services/xray.md
  - category: "Front-End Web and Mobile"
    services:
      - title: "AWS Amplify"
        url: /docs/pt/services/amplify.md
      - title: "Amazon API Gateway"
        url: /docs/pt/services/api-gateway.md
      - title: "AWS Device Farm"
        url: /docs/pt/services/device-farm.md
      - title: "Amazon Pinpoint"
        url: /docs/pt/services/pinpoint.md
  - category: "Machine Learning"
    services:
      - title: "Amazon Comprehend"
        url: /docs/pt/services/comprehend.md
      - title: "Amazon Forecast"
        url: /docs/pt/services/forecast.md
      - title: "Amazon Fraud Detector"
        url: /docs/pt/services/fraud-detector.md
      - title: "Amazon Kendra"
        url: /docs/pt/services/kendra.md
      - title: "Amazon Lex"
        url: /docs/pt/services/lex.md
      - title: "Amazon Polly"
        url: /docs/pt/services/polly.md
      - title: "Amazon Rekognition"
        url: /docs/pt/services/rekognition.md
      - title: "Amazon SageMaker"
        url: /docs/pt/services/sagemaker.md
      - title: "Amazon Textract"
        url: /docs/pt/services/textract.md
      - title: "Amazon Transcribe"
        url: /docs/pt/services/transcribe.md
      - title: "Amazon Translate"
        url: /docs/pt/services/translate.md
  - category: "Management and Governance"
    services:
      - title: "AWS Auto Scaling"
        url: /docs/pt/services/auto-scaling.md
      - title: "AWS CloudFormation"
        url: /docs/pt/services/cloudformation.md
      - title: "AWS CloudTrail"
        url: /docs/pt/services/cloudtrail.md
      - title: "Amazon CloudWatch"
        url: /docs/pt/services/cloudwatch.md
      - title: "AWS Command Line Interface (AWS CLI)"
        url: /docs/pt/services/cli.md
      - title: "AWS Compute Optimizer"
        url: /docs/pt/services/compute-optimizer.md
      - title: "AWS Config"
        url: /docs/pt/services/config.md
      - title: "AWS Control Tower"
        url: /docs/pt/services/control-tower.md
      - title: "AWS Health Dashboard"
        url: /docs/pt/services/health-dashboard.md
      - title: "AWS License Manager"
        url: /docs/pt/services/license-manager.md
      - title: "Amazon Managed Grafana"
        url: /docs/pt/services/managed-grafana.md
      - title: "Amazon Managed Service for Prometheus"
        url: /docs/pt/services/managed-prometheus.md
      - title: "AWS Management Console"
        url: /docs/pt/services/management-console.md
      - title: "AWS Organizations"
        url: /docs/pt/services/organizations.md
      - title: "AWS Proton"
        url: /docs/pt/services/proton.md
      - title: "AWS Service Catalog"
        url: /docs/pt/services/service-catalog.md
      - title: "AWS Systems Manager"
        url: /docs/pt/services/systems-manager.md
      - title: "AWS Trusted Advisor"
        url: /docs/pt/services/trusted-advisor.md
      - title: "AWS Well-Architected Tool"
        url: /docs/pt/services/well-architected-tool.md
  - category: "Media Services"
    services:
      - title: "Amazon Elastic Transcoder"
        url: /docs/pt/services/elastic-transcoder.md
      - title: "Amazon Kinesis Video Streams"
        url: /docs/pt/services/kinesis-video-streams.md
  - category: "Migration and Transfer"
    services:
      - title: "AWS Application Discovery Service"
        url: /docs/pt/services/application-discovery-service.md
      - title: "AWS Application Migration Service"
        url: /docs/pt/services/application-migration-service.md
      - title: "AWS Database Migration Service (AWS DMS)"
        url: /docs/pt/services/dms.md
      - title: "AWS DataSync"
        url: /docs/pt/services/datasync.md
      - title: "AWS Migration Hub"
        url: /docs/pt/services/migration-hub.md
      - title: "AWS Snow Family"
        url: /docs/pt/services/snow-family.md
      - title: "AWS Transfer Family"
        url: /docs/pt/services/transfer-family.md
  - category: "Networking and Content Delivery"
    services:
      - title: "AWS Client VPN"
        url: /docs/pt/services/client-vpn.md
      - title: "Amazon CloudFront"
        url: /docs/pt/services/cloudfront.md
      - title: "AWS Direct Connect"
        url: /docs/pt/services/direct-connect.md
      - title: "Elastic Load Balancing (ELB)"
        url: /docs/pt/services/elb.md
      - title: "AWS Global Accelerator"
        url: /docs/pt/services/global-accelerator.md
      - title: "AWS PrivateLink"
        url: /docs/pt/services/privatelink.md
      - title: "Amazon Route 53"
        url: /docs/pt/services/route-53.md
      - title: "AWS Site-to-Site VPN"
        url: /docs/pt/services/site-to-site-vpn.md
      - title: "AWS Transit Gateway"
        url: /docs/pt/services/transit-gateway.md
      - title: "Amazon VPC"
        url: /docs/pt/services/vpc.md
  - category: "Security, Identity, and Compliance"
    services:
      - title: "AWS Artifact"
        url: /docs/pt/services/artifact.md
      - title: "AWS Audit Manager"
        url: /docs/pt/services/audit-manager.md
      - title: "AWS Certificate Manager (ACM)"
        url: /docs/pt/services/certificate-manager.md
      - title: "AWS CloudHSM"
        url: /docs/pt/services/cloudhsm.md
      - title: "Amazon Cognito"
        url: /docs/pt/services/cognito.md
      - title: "Amazon Detective"
        url: /docs/pt/services/detective.md
      - title: "AWS Directory Service"
        url: /docs/pt/services/directory-service.md
      - title: "AWS Firewall Manager"
        url: /docs/pt/services/firewall-manager.md
      - title: "Amazon GuardDuty"
        url: /docs/pt/services/guardduty.md
      - title: "AWS IAM Identity Center (AWS Single Sign-On)"
        url: /docs/pt/services/identity-center.md
      - title: "AWS Identity and Access Management (IAM)"
        url: /docs/pt/services/iam.md
      - title: "Amazon Inspector"
        url: /docs/pt/services/inspector.md
      - title: "AWS Key Management Service (AWS KMS)"
        url: /docs/pt/services/kms.md
      - title: "Amazon Macie"
        url: /docs/pt/services/macie.md
      - title: "AWS Network Firewall"
        url: /docs/pt/services/network-firewall.md
      - title: "AWS Resource Access Manager (AWS RAM)"
        url: /docs/pt/services/ram.md
      - title: "AWS Secrets Manager"
        url: /docs/pt/services/secrets-manager.md
      - title: "AWS Security Hub"
        url: /docs/pt/services/security-hub.md
      - title: "AWS Shield"
        url: /docs/pt/services/shield.md
      - title: "AWS WAF"
        url: /docs/pt/services/waf.md
  - category: "Serverless"
    services:
      - title: "AWS AppSync"
        url: /docs/pt/services/appsync.md
      - title: "AWS Fargate"
        url: /docs/pt/services/fargate.md
      - title: "AWS Lambda"
        url: /docs/pt/services/lambda.md
